package de.mhus.osgi.sop.api.foundation.model;

import de.mhus.lib.basics.consts.Identifier;
import de.mhus.lib.basics.consts.ConstBase;
/**
 * File created by mhu const generator. Changes will be overwritten.
 **/
public class SopData_ extends ConstBase {

public static final Identifier ARCHIVED = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "archived");
public static final Identifier CLASS_NAME = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "de.mhus.osgi.sop.api.foundation.model.SopData");
public static final Identifier CLASS_PATH = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "de.mhus.osgi.sop.api.foundation.model.SopData");
public static final Identifier DATA = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "data");
public static final Identifier DUE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "due");
public static final Identifier FIELD_ARCHIVED = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "archived");
public static final Identifier FIELD_DATA = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "data");
public static final Identifier FIELD_DUE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "due");
public static final Identifier FIELD_FOREIGN_DATE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foreignDate");
public static final Identifier FIELD_FOREIGN_ID = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foreignId");
public static final Identifier FIELD_FOUNDATION = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foundation");
public static final Identifier FIELD_IS_PUBLIC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isPublic");
public static final Identifier FIELD_IS_WRITABLE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isWritable");
public static final Identifier FIELD_LAST_SYNC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSync");
public static final Identifier FIELD_LAST_SYNC_MSG = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSyncMsg");
public static final Identifier FIELD_LAST_SYNC_TRY = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSyncTry");
public static final Identifier FIELD_STATUS = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "status");
public static final Identifier FIELD_TYPE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "type");
public static final Identifier FIELD_VALUE0 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value0");
public static final Identifier FIELD_VALUE1 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value1");
public static final Identifier FIELD_VALUE2 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value2");
public static final Identifier FIELD_VALUE3 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value3");
public static final Identifier FIELD_VALUE4 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value4");
public static final Identifier FIELD_VALUE5 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value5");
public static final Identifier FIELD_VALUE6 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value6");
public static final Identifier FIELD_VALUE7 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value7");
public static final Identifier FIELD_VALUE8 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value8");
public static final Identifier FIELD_VALUE9 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value9");
public static final Identifier FOREIGN_DATE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foreignDate");
public static final Identifier FOREIGN_ID = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foreignId");
public static final Identifier FOUNDATION = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "foundation");
public static final Identifier IS_PUBLIC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isPublic");
public static final Identifier IS_WRITABLE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isWritable");
public static final Identifier LAST_SYNC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSync");
public static final Identifier LAST_SYNC_MSG = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSyncMsg");
public static final Identifier LAST_SYNC_TRY = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "lastSyncTry");
public static final Identifier METHOD_FIND_PARENT_OBJECT = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "findParentObject");
public static final Identifier METHOD_GET_DATA = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getData");
public static final Identifier METHOD_GET_DUE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getDue");
public static final Identifier METHOD_GET_FOREIGN_DATE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getForeignDate");
public static final Identifier METHOD_GET_FOREIGN_ID = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getForeignId");
public static final Identifier METHOD_GET_FOUNDATION = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getFoundation");
public static final Identifier METHOD_GET_LAST_SYNC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getLastSync");
public static final Identifier METHOD_GET_LAST_SYNC_MSG = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getLastSyncMsg");
public static final Identifier METHOD_GET_LAST_SYNC_TRY = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getLastSyncTry");
public static final Identifier METHOD_GET_STATUS = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getStatus");
public static final Identifier METHOD_GET_TYPE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getType");
public static final Identifier METHOD_GET_VALUE0 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue0");
public static final Identifier METHOD_GET_VALUE1 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue1");
public static final Identifier METHOD_GET_VALUE2 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue2");
public static final Identifier METHOD_GET_VALUE3 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue3");
public static final Identifier METHOD_GET_VALUE4 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue4");
public static final Identifier METHOD_GET_VALUE5 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue5");
public static final Identifier METHOD_GET_VALUE6 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue6");
public static final Identifier METHOD_GET_VALUE7 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue7");
public static final Identifier METHOD_GET_VALUE8 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue8");
public static final Identifier METHOD_GET_VALUE9 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "getValue9");
public static final Identifier METHOD_IS_ARCHIVED = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isArchived");
public static final Identifier METHOD_IS_IS_PUBLIC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isIsPublic");
public static final Identifier METHOD_IS_IS_WRITABLE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "isIsWritable");
public static final Identifier METHOD_SET_ARCHIVED = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setArchived");
public static final Identifier METHOD_SET_DUE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setDue");
public static final Identifier METHOD_SET_FOREIGN_DATE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setForeignDate");
public static final Identifier METHOD_SET_FOREIGN_ID = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setForeignId");
public static final Identifier METHOD_SET_LAST_SYNC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setLastSync");
public static final Identifier METHOD_SET_LAST_SYNC_MSG = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setLastSyncMsg");
public static final Identifier METHOD_SET_LAST_SYNC_TRY = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setLastSyncTry");
public static final Identifier METHOD_SET_PUBLIC = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setPublic");
public static final Identifier METHOD_SET_STATUS = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setStatus");
public static final Identifier METHOD_SET_VALUE0 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue0");
public static final Identifier METHOD_SET_VALUE1 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue1");
public static final Identifier METHOD_SET_VALUE2 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue2");
public static final Identifier METHOD_SET_VALUE3 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue3");
public static final Identifier METHOD_SET_VALUE4 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue4");
public static final Identifier METHOD_SET_VALUE5 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue5");
public static final Identifier METHOD_SET_VALUE6 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue6");
public static final Identifier METHOD_SET_VALUE7 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue7");
public static final Identifier METHOD_SET_VALUE8 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue8");
public static final Identifier METHOD_SET_VALUE9 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setValue9");
public static final Identifier METHOD_SET_WRITABLE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "setWritable");
public static final Identifier METHOD_TO_STRING = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "toString");
public static final Identifier PROJECT_ARTIFACT = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "mhu-sop-api");
public static final Identifier PROJECT_DESCRIPTION = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "A set of tools to improve OSGi frameworks and karaf");
public static final Identifier PROJECT_GROUP = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "de.mhus.osgi");
public static final Identifier PROJECT_VERSION = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "1.3.4-SNAPSHOT");
public static final Identifier STATUS = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "status");
public static final Identifier TYPE = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "type");
public static final Identifier VALUE0 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value0");
public static final Identifier VALUE1 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value1");
public static final Identifier VALUE2 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value2");
public static final Identifier VALUE3 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value3");
public static final Identifier VALUE4 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value4");
public static final Identifier VALUE5 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value5");
public static final Identifier VALUE6 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value6");
public static final Identifier VALUE7 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value7");
public static final Identifier VALUE8 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value8");
public static final Identifier VALUE9 = new Identifier(de.mhus.osgi.sop.api.foundation.model.SopData.class, "value9");

}