package de.mhus.osgi.sop.api.foundation.model;

import de.mhus.lib.basics.consts.Identifier;
import de.mhus.lib.basics.consts.ConstBase;
/**
 * File created by mhu const generator. Changes will be overwritten.
 **/
public class SopData_ extends ConstBase {

public static final Identifier ARCHIVED = new Identifier("archived");
public static final Identifier CLASS_NAME = new Identifier("de.mhus.osgi.sop.api.foundation.model.SopData");
public static final Identifier CLASS_PATH = new Identifier("de.mhus.osgi.sop.api.foundation.model.SopData");
public static final Identifier DATA = new Identifier("data");
public static final Identifier DUE = new Identifier("due");
public static final Identifier FIELD_ARCHIVED = new Identifier("archived");
public static final Identifier FIELD_DATA = new Identifier("data");
public static final Identifier FIELD_DUE = new Identifier("due");
public static final Identifier FIELD_FOREIGNDATE = new Identifier("foreignDate");
public static final Identifier FIELD_FOREIGNID = new Identifier("foreignId");
public static final Identifier FIELD_FOUNDATION = new Identifier("foundation");
public static final Identifier FIELD_ISPUBLIC = new Identifier("isPublic");
public static final Identifier FIELD_ISWRITABLE = new Identifier("isWritable");
public static final Identifier FIELD_LASTSYNC = new Identifier("lastSync");
public static final Identifier FIELD_LASTSYNCMSG = new Identifier("lastSyncMsg");
public static final Identifier FIELD_LASTSYNCTRY = new Identifier("lastSyncTry");
public static final Identifier FIELD_STATUS = new Identifier("status");
public static final Identifier FIELD_TYPE = new Identifier("type");
public static final Identifier FIELD_VALUE0 = new Identifier("value0");
public static final Identifier FIELD_VALUE1 = new Identifier("value1");
public static final Identifier FIELD_VALUE2 = new Identifier("value2");
public static final Identifier FIELD_VALUE3 = new Identifier("value3");
public static final Identifier FIELD_VALUE4 = new Identifier("value4");
public static final Identifier FIELD_VALUE5 = new Identifier("value5");
public static final Identifier FIELD_VALUE6 = new Identifier("value6");
public static final Identifier FIELD_VALUE7 = new Identifier("value7");
public static final Identifier FIELD_VALUE8 = new Identifier("value8");
public static final Identifier FIELD_VALUE9 = new Identifier("value9");
public static final Identifier FOREIGNDATE = new Identifier("foreignDate");
public static final Identifier FOREIGNID = new Identifier("foreignId");
public static final Identifier FOUNDATION = new Identifier("foundation");
public static final Identifier ISPUBLIC = new Identifier("isPublic");
public static final Identifier ISWRITABLE = new Identifier("isWritable");
public static final Identifier LASTSYNC = new Identifier("lastSync");
public static final Identifier LASTSYNCMSG = new Identifier("lastSyncMsg");
public static final Identifier LASTSYNCTRY = new Identifier("lastSyncTry");
public static final Identifier METHOD_FINDPARENTOBJECT = new Identifier("findParentObject");
public static final Identifier METHOD_GETDATA = new Identifier("getData");
public static final Identifier METHOD_GETDUE = new Identifier("getDue");
public static final Identifier METHOD_GETFOREIGNDATE = new Identifier("getForeignDate");
public static final Identifier METHOD_GETFOREIGNID = new Identifier("getForeignId");
public static final Identifier METHOD_GETFOUNDATION = new Identifier("getFoundation");
public static final Identifier METHOD_GETLASTSYNC = new Identifier("getLastSync");
public static final Identifier METHOD_GETLASTSYNCMSG = new Identifier("getLastSyncMsg");
public static final Identifier METHOD_GETLASTSYNCTRY = new Identifier("getLastSyncTry");
public static final Identifier METHOD_GETSTATUS = new Identifier("getStatus");
public static final Identifier METHOD_GETTYPE = new Identifier("getType");
public static final Identifier METHOD_GETVALUE0 = new Identifier("getValue0");
public static final Identifier METHOD_GETVALUE1 = new Identifier("getValue1");
public static final Identifier METHOD_GETVALUE2 = new Identifier("getValue2");
public static final Identifier METHOD_GETVALUE3 = new Identifier("getValue3");
public static final Identifier METHOD_GETVALUE4 = new Identifier("getValue4");
public static final Identifier METHOD_GETVALUE5 = new Identifier("getValue5");
public static final Identifier METHOD_GETVALUE6 = new Identifier("getValue6");
public static final Identifier METHOD_GETVALUE7 = new Identifier("getValue7");
public static final Identifier METHOD_GETVALUE8 = new Identifier("getValue8");
public static final Identifier METHOD_GETVALUE9 = new Identifier("getValue9");
public static final Identifier METHOD_ISARCHIVED = new Identifier("isArchived");
public static final Identifier METHOD_ISISPUBLIC = new Identifier("isIsPublic");
public static final Identifier METHOD_ISISWRITABLE = new Identifier("isIsWritable");
public static final Identifier METHOD_SETARCHIVED = new Identifier("setArchived");
public static final Identifier METHOD_SETDUE = new Identifier("setDue");
public static final Identifier METHOD_SETFOREIGNDATE = new Identifier("setForeignDate");
public static final Identifier METHOD_SETFOREIGNID = new Identifier("setForeignId");
public static final Identifier METHOD_SETLASTSYNC = new Identifier("setLastSync");
public static final Identifier METHOD_SETLASTSYNCMSG = new Identifier("setLastSyncMsg");
public static final Identifier METHOD_SETLASTSYNCTRY = new Identifier("setLastSyncTry");
public static final Identifier METHOD_SETPUBLIC = new Identifier("setPublic");
public static final Identifier METHOD_SETSTATUS = new Identifier("setStatus");
public static final Identifier METHOD_SETVALUE0 = new Identifier("setValue0");
public static final Identifier METHOD_SETVALUE1 = new Identifier("setValue1");
public static final Identifier METHOD_SETVALUE2 = new Identifier("setValue2");
public static final Identifier METHOD_SETVALUE3 = new Identifier("setValue3");
public static final Identifier METHOD_SETVALUE4 = new Identifier("setValue4");
public static final Identifier METHOD_SETVALUE5 = new Identifier("setValue5");
public static final Identifier METHOD_SETVALUE6 = new Identifier("setValue6");
public static final Identifier METHOD_SETVALUE7 = new Identifier("setValue7");
public static final Identifier METHOD_SETVALUE8 = new Identifier("setValue8");
public static final Identifier METHOD_SETVALUE9 = new Identifier("setValue9");
public static final Identifier METHOD_SETWRITABLE = new Identifier("setWritable");
public static final Identifier METHOD_TOSTRING = new Identifier("toString");
public static final Identifier PROJECT_ARTIFACT = new Identifier("mhu-sop-api");
public static final Identifier PROJECT_DESCRIPTION = new Identifier("A set of tools to improve OSGi frameworks and karaf");
public static final Identifier PROJECT_GROUP = new Identifier("de.mhus.osgi");
public static final Identifier PROJECT_VERSION = new Identifier("1.3.4-SNAPSHOT");
public static final Identifier STATUS = new Identifier("status");
public static final Identifier TYPE = new Identifier("type");
public static final Identifier VALUE0 = new Identifier("value0");
public static final Identifier VALUE1 = new Identifier("value1");
public static final Identifier VALUE2 = new Identifier("value2");
public static final Identifier VALUE3 = new Identifier("value3");
public static final Identifier VALUE4 = new Identifier("value4");
public static final Identifier VALUE5 = new Identifier("value5");
public static final Identifier VALUE6 = new Identifier("value6");
public static final Identifier VALUE7 = new Identifier("value7");
public static final Identifier VALUE8 = new Identifier("value8");
public static final Identifier VALUE9 = new Identifier("value9");
}